### ISSUE TITLE
HTTP compression not supported

### ISSUE THREAD

**Issue by kelson42** [kiwix/k8s#10]
Tested on https://wiki.kiwix.org with https://www.whatsmyip.org/http-compression-test/

AFAIK this is a regression in the reverse proxy.

**Comment by rgaudin** [comment]
No, either it wasn't compressed or Sloppy's proxy enabled it.

I've fixed it in https://github.com/offspot/mediawiki-docker/commit/a5c0dc314403ad1dcbfb5ee2439dded40db5efc7 and deployed it on both [openzim](https://www.whatsmyip.org/http-compression-test/?url=aHR0cHM6Ly93aWtpLm9wZW56aW0ub3Jn) and [kiwix](https://www.whatsmyip.org/http-compression-test/?url=aHR0cHM6Ly93aWtpLmtpd2l4Lm9yZw==) wikis.

I think it's good practice to fix this upstream rather than enabling it in our reverse proxy: leaves upstream project un-optimized, us un-aware and removes some control: what if a service needs to have gzip turned off?
