### ISSUE TITLE
Direct APK download is buggy on kiwix.org

### ISSUE THREAD

**Issue by jayb-g** [kiwix/k8s#137]
**Describe the bug**

The direct download link for kiwix android listed on https://kiwix.org/en/applications as [Direct APK](https://download.kiwix.org/release/kiwix-android/kiwix.apk) sometimes starts download as kiwix-3.7.1.txt sometimes as kiwix-3.7.1.zip and sometimes as kiwix-3.7.1.apk

**Expected behavior**

Should download latest version as .apk file every time. 

**Steps to reproduce the behavior:**
1. Open https://kiwix.org/en/applications on latest versions of firefox and android(14) (I'm using Firefox, but maybe same behavior for chrome)
2. In the 'Kiwix for Android' section, click on 'Direct APK' button
3. The download prompt will show the filename before starting the download. 
4. Make note of the filename and extension, cancel the download and repeat from step 2

**Screenshots**

**Environment**
- Version of Kiwix Android : kiwix web (kiwix.org)
- Device : 
- OS version : 

**Logs**
I have the screen recorded but don't know how to upload here. It just shows option to link to online media file.

**Comment by kelson42** [comment]
Transferring to the « operations » repository.

**Comment by rgaudin** [comment]
Probably one or several mirrors not serving APK with the appropriate Content-Type

**Comment by rgaudin** [comment]
Indeed

https://md.mirrors.hacktegic.com/kiwix-md/release/kiwix-android/kiwix-3.7.1.apk
Missing CT

https://mirrors.dotsrc.org/kiwix/release/kiwix-android/kiwix-3.7.1.apk
Missing CT

https://ftp.nluug.nl/pub/kiwix/release/kiwix-android/kiwix-3.7.1.apk
Content-Type: text/plain; charset=UTF-8

https://ftp.fau.de/kiwix/release/kiwix-android/kiwix-3.7.1.apk
Content-Type: application/vnd.android.package-archive

https://mirror.download.kiwix.org/release/kiwix-android/kiwix-3.7.1.apk
content-type: application/vnd.android.package-archive

https://mirror-sites-in.mblibrary.info/mirror-sites/download.kiwix.org/release/kiwix-android/kiwix-3.7.1.apk
Content-Type: application/vnd.android.package-archive

https://mirror-sites-fr.mblibrary.info/mirror-sites/download.kiwix.org/release/kiwix-android/kiwix-3.7.1.apk
Content-Type: application/vnd.android.package-archive

https://mirror-sites-ca.mblibrary.info/mirror-sites/download.kiwix.org/release/kiwix-android/kiwix-3.7.1.apk
Content-Type: application/vnd.android.package-archive

I suppose the culprit is ftp.nluug.nl. I'll contact them. @jayb-g @gouri-panda can you test the first two mirrors (those not setting a Content-Type at all) to see how it behaves?

**Comment by kelson42** [comment]
> can you test the first two mirrors (those not setting a Content-Type at all) to see how it behaves?

On iOS, download starts properly.

**Comment by rgaudin** [comment]
Thank you @gouri-panda ; I am writting to them as well then

**Comment by artiommocrenco** [comment]
For the hacktegic mirror, I added these two lines to Caddyfile (the config):
```
@apk path *.apk
header @apk Content-Type "application/vnd.android.package-archive"
```
Apologies for the inconsistency it was introducing.

**Comment by rgaudin** [comment]
Works fine with every other browser I tested on iOS (including Firefox). Looks like a FF Focus bug. You shall report it.

**Comment by jayb-g** [comment]
@rgaudin all first 3 links return .apk download now

**Comment by AndersTrier** [comment]
I just fixed it for dotsrc.org:
```
$ curl --silent --head https://mirrors.dotsrc.org/kiwix/release/kiwix-android/kiwix-3.7.1.apk | grep content-type
content-type: application/vnd.android.package-archive
```

**Comment by jayb-g** [comment]
@AndersTrier Now its downloading apk on FF

**Comment by rgaudin** [comment]
Thank you @AndersTrier ; we're all good now.
