### ISSUE TITLE
Add README to download.kiwix.org/library/

### ISSUE THREAD

**Issue by kelson42** [kiwix/k8s#30]
With explanation on how library_zim.xml consumers should use OPDS API instead

**Comment by rgaudin** [comment]
Done http://download.kiwix.org/library/README

**Comment by holta** [comment]
@rgaudin is the following supposed to be live?

> Official Kiwix ZIM Catalog is at https://library.kiwix.org/catalog/v2/

(Or is this a typo in the [README](http://download.kiwix.org/library/README) ?)

**Comment by tim-moody** [comment]
I have been using https://library.kiwix.org/catalog/v2/root.xml for about a year. Is that OK on an ongoing basis?

**Comment by rgaudin** [comment]
Do you mean https://library.kiwix.org/catalog/v1/root.xml @tim-moody  ? That's not the same

**Comment by tim-moody** [comment]
@rgaudin sorry I misspoke. I'm using just https://library.kiwix.org/catalog/root.xml, which I thought was OPDS

**Comment by rgaudin** [comment]
It is indeed. This is not deprecated at the moment but I'd still invite you to switch to the v2 endpoint.
I believe `https://library.kiwix.org/catalog/v2/entries?count=-1` is equivalent.

**Comment by tim-moody** [comment]
OK. I can try that change. The entry schema I am parsing looks to be the same.

**Comment by tim-moody** [comment]
We now see that the accented characters in https://library.kiwix.org/catalog/v2/entries?count=-1 are different than in  https://library.kiwix.org/catalog/root.xml

For example if you search for wikipedia_es_mathematics_maxi you will see that the new catalog has

<title>MatemÃ¡ticas por Wikipedia</title> whereas the old catalog had

<title>Matemáticas por Wikipedia</title>

I think the second is correct and wonder if the first is not utf-8.

(I am reading both strings directly from the xml in Chrome browser on Win 10.)
(same in edge; can't tell in FF because it does a download)

**Comment by tim-moody** [comment]
BUT. If I wget the file in linux and open in nano and search for the same zim, the title looks OK. So is there a decode that needs to be done when reading the OPDS?

**Comment by kelson42** [comment]
> We now see that the accented characters in https://library.kiwix.org/catalog/v2/entries?count=-1 are different than in https://library.kiwix.org/catalog/root.xml

@tim-moody Please open a ticket in kiwix/libkiwix repository. Sounds oike a HTTP/HTML header problem.

**Comment by kelson42** [comment]
@tim-moody Done at https://github.com/kiwix/libkiwix/issues/941
