### ISSUE TITLE
Add centralized log repository and dashboard

### ISSUE THREAD

**Issue by rgaudin** [kiwix/k8s#5]
There are several providers in this field and I haven't invested time in comparing them but I like Grafana Loki:
- Only timestamps + labels are indexed so you can store data anywhere (like in S3)
- OSS
- SaaS option available to try-it-out first, with [a free plan](https://grafana.com/pricing/)
- Visualizer is Grafana which we may use for metrics monitoring

**Comment by kelson42** [comment]
> * SaaS option available to try-it-out first, with [a free plan](https://grafana.com/pricing/)

Yes, this could work.

**Comment by benoit74** [comment]
> One other important question is: for k8s logs or as well for app logs

For both from my PoV, we need to understand what happens in k8s (container starts / stops / exhausted resources / ...) and in apps

> SaaS option available to try-it-out first, with [a free plan](https://grafana.com/pricing/)

This could be a quick win. A personally like Grafana suite, especially when it comes to Loki for logs management.

**Comment by kelson42** [comment]
@benoit74 Lets go then!

**Comment by benoit74** [comment]
@kelson42 What is the priority compared to other topics on my plate which I could start / continue to work on as well (ory.sh, offspot/metrics, mail issues, zimfarm issues)?

**Comment by kelson42** [comment]
No prio on my side, but maybe on yours?

**Comment by rgaudin** [comment]
I have no experience with it so my understanding of the required workload is limited but I think it's reasonable.
Having this before the now approaching k8s migration will be very useful to help diagnose post-migration errors as there will be a window during which we'll question every issue's relatedness to the migration.

**Comment by benoit74** [comment]
Monitoring stack is up and running at https://kiwixorg.grafana.net

Entrypoint for details about infra configuration is at https://github.com/kiwix/k8s/wiki/Monitoring#grafana

You might for instance analyze [Zimfarm API logs](https://kiwixorg.grafana.net/explore?panes=%7B%22yh9%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22zimfarm%5C%22,%20pod%3D~%5C%22api-deployment-.%2A%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1) or [k8s node usage efficiency](https://kiwixorg.grafana.net/d/8f43c8565d6575678e22e36e36bb8bfc/efficiency?orgId=1&refresh=30s) (among **many many many** other things).

Logs are duplicated because I restarted the log agent many times this morning and it looks like it caused logs duplication. Since we are on an unlimited free trial, I opened a support ticket: https://grafana.com/orgs/kiwixorg/tickets/103883

I let the system stabilize a bit and will probably reconfigure it a bit to include Certbot + Postgresql integrations to grab more details about those services (will depend on our current Grafana resource usage, to ensure that it stays under control)

**Comment by benoit74** [comment]
I've also posted a question regarding data usage on the forum: https://community.grafana.com/t/what-happens-when-my-usage-exceed-the-free-plan-limitations/102795

**Comment by benoit74** [comment]
Finally transferred the data usage question to a support ticket: https://grafana.com/orgs/kiwixorg/tickets/103901

Decision has been made last Friday to pay for Grafana for now, to dive deeper in the product and confirm it fits our need. While our current usage indicates that the Pro offer will cost at least 29$ / month, less than 50$ in any case, Stéphane is investigating with Grafana whether they have a specific offer for non-profits.

**Comment by benoit74** [comment]
I will duplicate support tickets here for backup / easier access.

**Comment by benoit74** [comment]
Ticket [103883](https://grafana.com/orgs/kiwixorg/tickets/103883)

### My inquiry:

Hello,

I'm just starting to configure a new Grafana Cloud account to monitor our k8s cluster and its workloads.

What happened?
I deployed Grafana k8s-monitoring helm chart progressively this morning to check by small steps that everything was working fine. I did this by progressively moving enabled values from false to true

Since the Agent configuration was modified many times in this process, I decided to restart the Agent pods: the global one deployed as a statefulset and the 4 agent-logs (we have 4 k8s nodes) ones deployed as a daemonset.

I now realize that logs are duplicated in Loki. It looks like everytime the agent restarted it sent again the logs.

What was expected to happen?
I don't know exactly what I'm supposed to expect. At least I would prefer to not have duplicated logs, but maybe this is normal or this is due to something I did wrong.

Version numbers (grafana, prometheus, graphite, plugins, operating system, etc.):

    Grafana Cloud, so no idea about Grafana/Loki/Prometheus versions)
    Grafana Agent v0.35.2

### Reply from Grafana:

Marian Dima
September 5, 2023 10:18 AM
Hello there,
 
I hope you are doing well!
 
My name is Marian Dima and I am the Support Engineer who is going to assist you with this case going forward.
 
From the description you have provided, I would say that the behavior is expected.
 
Every time the Agent will be restarted, it will go through the config file and scrape the logs from all the defined targets.
 
A similar issue was described here -> https://github.com/grafana/agent/issues/2537 where a container in restarting state was sending the logs over and over again.
 
The suggested fix for this was to set the `refresh_interval` to a higher value.
 
Of course, if there are additional questions or concerns from your side regarding this topic, please let me know.

**Comment by benoit74** [comment]
We have switched to a Cloud Pro account, setup is now complete.

**Comment by kelson42** [comment]
Big Kudos to all people involved in this @benoit74 @rgaudin @Popolechien
